### ISSUE TITLE
rename test module & add library module to tests

### ISSUE THREAD

**Issue by matonix** [matonix/stack-templates#2]
ref. https://gist.github.com/algas/0ec303769e09a8c9188b83a3d7a8990c#file-hspec-hpack-hsfiles

```yaml
tests:
  {{name}}-test:
    source-dirs:
      - test
    main: Spec.hs
    dependencies:
      - {{name}}
      - hspec
```
